<?php
/**
 * @file
 * Code for the Dir Topweb feature.
 */

include_once 'dir_topweb.features.inc';

/**
 * @file
 * Dir Topweb module file.
 */

// -----------------------------------------------------------------------------
// General hook

/**
 * Implements hook_ctools_plugin_directory().
 */
function dir_topweb_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'eck' && $plugin_type == 'property_behavior') {
    return $owner . '/' . $plugin_type;
  }
}

// -----------------------------------------------------------------------------
// EntityMetadata property callback

// -----------------
// dir_link property

/**
 * 'getter callback' for dir_link rank property.
 */
function dir_link_rank_entity_property_getter($data, array $options, $name, $type, $info) {
  return KtoolsEntityProperty::queryEntities('dir_rank', 'link', $data->id);
}

/**
 * 'getter callback' for dir_link ranks property.
 */
function dir_link_ranks_entity_property_getter($data, array $options, $name, $type, $info) {
  $entity_ids = KtoolsEntityProperty::queryEntities('dir_rank', 'link', $data->id);
  $ranks = KtoolsEntity::listByBundleKey('dir_rank', $entity_ids);

  return $ranks;
}

/**
 * 'getter callback' for dir_link ranking property.
 */
function dir_link_ranking_entity_property_getter($data, array $options, $name, $type, $info) {
  $link_wrapper = entity_metadata_wrapper('dir_link', $data);
  $ranking = 0;
  foreach ($link_wrapper->rank as $rank_wrapper) {
    $rank = $rank_wrapper->value();
    $config = eck_extras_entity_get_bundle_config($rank);
    $ranking += $rank->score * $config['score']['factor'];
  }

  return $ranking;
}
